---
services:
  db:
    image: postgres:18
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes: [postgres_data:/var/lib/postgresql]
    ports: [5432:5432]
    env_file: [.env]
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web:
    depends_on:
      db:
        condition: service_healthy
    env_file: [.env]
    build: .
    ports: [8080:8080]
    volumes: [uploads_data:/usr/src/app/data/uploads]
volumes:
  postgres_data:
  uploads_data:
