---
services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes: ['${HOME}/docker/kuvagalleria/postgres_data:/var/lib/postgresql']
    ports: [5432:5432]
    env_file: [.env]
  pgAdmin:
    image: dpage/pgadmin4:9.11.0
    env_file: [.env]
    environment:
      PGADMIN_DISABLE_POSTFIX: true
    ports: [5433:80]
    volumes: ['${HOME}/docker/kuvagalleria/pgadmin_data:/var/lib/pgadmin']
volumes:
  pgadmin_data:
  postgres_data:
