FROM golang:1.25.5
WORKDIR /usr/src/app

RUN go install github.com/air-verse/air@latest

RUN apt-get -y update && apt-get -y --no-install-recommends install unzip=6.0-29
RUN wget -qO- https://bun.com/install | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
ENV PATH="/root/.bun/bin:$PATH"

COPY go.mod go.sum ./
RUN go mod download

COPY package.json bun.lock ./
RUN bun i --frozen-lockfile

EXPOSE 8080
CMD ["air"]
